#pragma once
#include "artgen/IAlgorithm.h"
#include "artgen/Palette.h"
#include <cstdint>
#include <vector>

namespace artgen {

// Plasma fractal generated by the Diamond-Square (midpoint displacement) algorithm.
// Builds a (2^octaves + 1)^2 heightfield grid, then samples it bilinearly for
// each output pixel.
//
// Produces organic cloud/terrain/marble textures that complement the FBM noise
// algorithm.  Not tileable.
class PlasmaAlgorithm : public IAlgorithm {
public:
    float    roughness = 0.5f;  // amplitude scale per level [0,1]; lower = smoother
    uint32_t seed      = 42;
    int      octaves   = 8;     // grid size = 2^octaves + 1  (8 → 257×257)
    Palette  palette;

    PlasmaAlgorithm();
    const char* name()        const override { return "plasma"; }
    bool        is_tileable() const override { return false; }
    void render(PixelBuffer& buf, const Viewport& vp) const override;
    void set_palette_phase(float p) override { palette.phase = p; }

private:
    static float bilinear(const std::vector<float>& grid, int gsize,
                          float gx, float gy);
};

} // namespace artgen
